export const COPYRIGHT_ENTITY = '\u00a9'; // (c)
export const H_ELLIPSIS_ENTITY = '\u2026'; // ...
export const VERTICAL_LINE_ENTITY = '\u007c'; // |
export const GEARS_ENTITY = '\u2699'; // ⚙
export const BRIGHT_ENTITY = '🔆'; // '\1F506'; // 🔆
export const SUN_ENTITY = '\u2600'; // ☀️
export const WHITE_SUN_ENTITY = '\u263C'; // ☼
export const CRESCENT_MOON_ENTITY = '🌙'; // '\1F319'; // 🌙
export const WAXING_CRESCENT_MOON_ENTITY = '🌒'; // '\1F312'; // 🌒
export const WANING_CRESCENT_MOON_ENTITY = '🌘'; // '\1F318'; // 🌘
export const FLASHLIGHT_ENTITY = '🔦'; // '\1F526'; // 🔦
export const CAMERA_ENTITY = '📷'; // '\1F4F7'; // 📷
export const CAMERA_FLASH_ENTITY = '📸'; // '\1F4F8'; // 📸
